name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Flutter Build
        run: |
          flutter pub get
          flutter config --enable-web
          flutter build web --release

      # Change: Ensure npm is available and install Firebase CLI globally
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase --version  # Verify installation

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        working-directory: firebase
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
