name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      # Install project dependencies and build for web
      - name: Flutter Build
        run: |
          flutter pub get
          flutter config --enable-web
          flutter build web --release

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # List directory structure for debugging
      - name: List directory structure
        run: ls -R /home/runner/work/rasondoAppFlutter/rasondoAppFlutter

      # Navigate to the correct directory
      - name: Navigate to Firebase project directory
        run: cd /home/runner/work/rasondoAppFlutter/rasondoAppFlutter

      # Verify firebase.json exists
      - name: Verify firebase.json
        run: ls -l /home/runner/work/rasondoAppFlutter/rasondoAppFlutter/firebase.json

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
